name              'imvlandau'
maintainer        'Sufian Abu-Rab'
maintainer_email  's.aburab@gmail.com'
source_url        'https://github.com/imvlandau/imvlandau'
issues_url        'https://github.com/imvlandau/imvlandau/issues'
license           'Proprietary - All Rights Reserved'
description       'Installs/Configures imvlandau'
long_description  IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version           '0.1.0'
chef_version      '>= 14.0'

depends           'system'
depends           'aws'
depends           'line'
depends           'apache2'
depends           'postgresql'
depends           'acme'
